In [66]:
# Cohort 1

In [67]:
# Import
import pandas as pd

In [68]:
# Path

csv_cohort1_a1 = '../../dataset/cohort1/A1_Questionnaire_Cohort1_Baseline_data.csv'
csv_cohort1_b1 = '../../dataset/cohort1/B1_Sample_Collection_Form_Cohort1_Baseline_data.csv'
csv_cohort1_c1 = '../../dataset/cohort1/C1_LabResult_Cohort1_Baseline_ELISA_data.csv'

In [69]:
df_a1 = pd.read_csv(csv_cohort1_a1, low_memory=False)
df_b1 = pd.read_csv(csv_cohort1_b1, low_memory=False)
df_c1 = pd.read_csv(csv_cohort1_c1, low_memory=False)

df_a1.head()

,SubmissionDate,I1d,I2s,I3e,I4d,I5u,A1,A1manual,A1m_s,A1m_cal,...,KEY,SubmitterID,SubmitterName,AttachmentsPresent,AttachmentsExpected,Status,ReviewState,DeviceID,Edits,FormVersion
0,2026-07-31T09:06:18.289Z,2026-07-31,2026-07-31T15:54:15.597+07:00,2026-07-31T16:06:17.498+07:00,collect:RQ1eyOTTgb72DTff,T12,DEM1-SR-0780,NaN,NaN,NaN,...,uuid:94bd2aa5-e835-47af-b3b0-0d739edb2fc1,167,T12,0,0,NaN,NaN,collect:RQ1eyOTTgb72DTff,0,v20
1,2026-07-31T08:53:16.761Z,2026-07-31,2026-07-31T15:47:53.158+07:00,2026-07-31T15:53:09.236+07:00,collect:HWmr5IpdBFgGHeiN,T03,DEM1-SR-0779,NaN,NaN,NaN,...,uuid:f73bc189-57a2-4ddb-bd60-4a3475c4e36e,158,T03,0,0,NaN,NaN,collect:HWmr5IpdBFgGHeiN,0,v20
2,2026-07-31T08:36:28.343Z,2026-07-31,2026-07-31T15:35:22.063+07:00,2026-07-31T15:36:27.546+07:00,collect:RQ1eyOTTgb72DTff,T12,DEM1-SR-0780,NaN,NaN,NaN,...,uuid:77e17001-d76d-4c1c-be46-f4e90dad82e2,167,T12,0,0,NaN,NaN,collect:RQ1eyOTTgb72DTff,0,v20
3,2026-07-31T08:34:26.798Z,2026-07-31,2026-07-31T15:33:37.511+07:00,2026-07-31T15:34:25.991+07:00,collect:RQ1eyOTTgb72DTff,T12,DEM1-SR-0779,NaN,NaN,NaN,...,uuid:fd0ff7f4-65a6-40a4-9361-f33e9148225c,167,T12,0,0,NaN,NaN,collect:RQ1eyOTTgb72DTff,0,v20
4,2026-07-31T05:36:11.290Z,2026-07-31,2026-07-31T11:19:58.566+07:00,2026-07-31T11:33:21.868+07:00,collect:HWmr5IpdBFgGHeiN,T03,DEM1-SR-0778,NaN,NaN,NaN,...,uuid:de6138ba-ad98-4a7b-9e3a-e187d3153c6e,158,T03,0,0,NaN,NaN,collect:HWmr5IpdBFgGHeiN,0,v20

In [70]:
# df_a1[df_a1['A1'].map(df_a1['A1'].value_counts()) == 2].head()
# df_a1[df_a1['A1'] == 'DEM1-SR-0780'].head()

In [71]:
def make_list_by_id(df):
    df = df.copy()
    manual_id = df['A1manual'].notna()
    df.loc[manual_id, 'A1'] = df.loc[manual_id, 'A1manual']

    return (
        df
        .rename(columns={'A1': 'ID'})
        .groupby('ID', as_index=False)
        .agg(lambda col: col.dropna().tolist())
    )


def prefix_columns(df, prefix):
    return df.rename(columns={col: f'{prefix}_{col}' for col in df.columns if col != 'ID'})


df_a1_list = make_list_by_id(df_a1)
df_b1_list = make_list_by_id(df_b1)
df_c1_list = make_list_by_id(df_c1)

df_cohort1 = (
    prefix_columns(df_a1_list, 'a1')
    .merge(prefix_columns(df_b1_list, 'b1'), on='ID', how='outer')
    .merge(prefix_columns(df_c1_list, 'c1'), on='ID', how='outer')
)

df_cohort1.head()

/var/folders/5s/l5p9dsyx21x7p61xtn_jz3pm0000gn/T/ipykernel_95743/967003752.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .agg(lambda col: col.dropna().tolist())

,ID,a1_SubmissionDate,a1_I1d,a1_I2s,a1_I3e,a1_I4d,a1_I5u,a1_A1manual,a1_A1m_s,a1_A1m_cal,...,c1_KEY,c1_SubmitterID,c1_SubmitterName,c1_AttachmentsPresent,c1_AttachmentsExpected,c1_Status,c1_ReviewState,c1_DeviceID,c1_Edits,c1_FormVersion
0,DEM1-PP-0001,"[2025-11-21T01:02:45.038Z, 2025-11-20T03:49:18...","[2025-11-20, 2025-11-20, 2025-11-20]","[2025-11-20T19:31:38.271+07:00, 2025-11-20T09:...","[2025-11-21T08:02:44.007+07:00, 2025-11-20T10:...","[collect:9qMhME16PHTSvgub, collect:9qMhME16PHT...","[T02, T02, T05]",[DEM1-PP-0001],[DEM1-PP-],[1.0],...,[uuid:e8e31970-3420-4668-82ad-2e5802fefda5],[171],[T16],[0],[0],[],[],[collect:1OmvGirXCAZAfOcI],[0],[v6]
1,DEM1-PP-0002,"[2025-11-21T08:23:52.422Z, 2025-11-21T07:04:55...","[2025-11-21, 2025-11-21]","[2025-11-21T14:09:29.666+07:00, 2025-11-21T14:...","[2025-11-21T15:23:42.972+07:00, 2025-11-21T14:...","[collect:HWmr5IpdBFgGHeiN, collect:AjALCnSN3bS...","[T03, T05]",[],[],[],...,[uuid:fd9e9a64-4951-4d4a-84a4-5e35f3deef64],[171],[T16],[0],[0],[],[],[collect:1OmvGirXCAZAfOcI],[0],[v6]
2,DEM1-PP-0003,"[2025-11-26T08:40:07.980Z, 2025-11-21T09:03:30...","[2025-11-26, 2025-11-21, 2025-11-21]","[2025-11-26T15:38:20.543+07:00, 2025-11-21T14:...","[2025-11-26T15:40:07.176+07:00, 2025-11-21T16:...","[collect:T5QvhN5vxk4nqGua, collect:HWmr5IpdBFg...","[T06, T03, T05]",[DEM1-PP-0003],[DEM1-PP-],[3.0],...,[uuid:6edf578d-059e-4b9b-8320-8f6801275ad2],[170],[T15],[0],[0],[],[],[collect:wvNQjIeyEj3rls50],[0],[v6]
3,DEM1-PP-0004,"[2025-11-26T02:44:11.810Z, 2025-11-25T02:32:31...","[2025-11-26, 2025-11-25, 2025-11-24, 2025-11-21]","[2025-11-26T09:42:20.278+07:00, 2025-11-25T09:...","[2025-11-26T09:44:11.120+07:00, 2025-11-25T09:...","[collect:T5QvhN5vxk4nqGua, collect:9qMhME16PHT...","[T06, T02, T07, T05]",[],[],[],...,[uuid:d954cc29-3591-4f07-8a72-b0a1fc52b7f7],[170],[T15],[0],[0],[],[],[collect:wvNQjIeyEj3rls50],[0],[v6]
4,DEM1-PP-0005,"[2025-12-31T09:00:32.126Z, 2025-12-02T01:53:36...","[2025-12-31, 2025-12-02, 2025-11-24]","[2025-12-31T15:57:20.393+07:00, 2025-12-02T08:...","[2025-12-31T16:00:30.482+07:00, 2025-12-02T08:...","[collect:T5QvhN5vxk4nqGua, collect:9qMhME16PHT...","[T06, T02, T02]",[],[],[],...,[uuid:b522fdd8-328c-42b4-9fe5-0d1e7b1762cb],[171],[T16],[0],[0],[],[],[collect:1OmvGirXCAZAfOcI],[0],[v6]

In [72]:
# df_a1[ df_a1['A1manual'].notna() ]

In [73]:
# df_a1_list.head()
# df_a1_list.columns.tolist()

In [74]:
# df_a1_list.info()
# print(len(df_a1_list))

# empty_list_counts = df_a1_list.apply(
#     lambda col: col.map(lambda value: isinstance(value, list) and len(value) == 0).sum()
# )

# columns_with_empty_lists = empty_list_counts[empty_list_counts > 0]
# columns_with_empty_lists
# df_a1_list[df_a1_list['A6_spc'].notna()]['A6_spc']