In [1]:
import requests
import pandas as pd
from io import StringIO
import utils as utils
from utils import *

In [ ]:
sheet_id = "1XuTFEkznzX6QAr4ZIk27vVSpTpbWtaU2"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"

df = pd.read_csv(url)
df['Participant ID'] = df['Participant ID'].str.strip()
df['Form'] = df['Form'].str.strip()

df

,Date report issue,Form,Participant ID,Correction,Status
0,24-Nov-25,A1,DEM1-PP-0034,"Delete this data submitted on 20 Nov 2025, it'...",NaN
1,25-Nov-25,A1,DEM1-PP-0009,C8. change 5 to 1 cuz the guardian change job ...,NaN
2,27-Nov-25,A4,DEM2-PP-0002,"I11. change 2 to 1 and \nI11med. note as ""Not ...",NaN
3,28-Nov-25,D1,DEM1-PP-0023,"A4. Age group, change 10-14 to 5-10",NaN
4,3-Dec-25,A4,DEM2-PP-0004,Delete this data because Dx was changed and co...,NaN
...,...,...,...,...,...
66,23-Apr-26,A1,DEM1-SR-0281,C3: changed Male to Female. ( Submit on 23-04-...,NaN
67,24-Apr-26,A1,DEM1-SR-0269,delete submission from T11 at 10:17 22.04.2026...,NaN
68,6-May-26,D1,DEM1-SR-0026,A3. Recruitment site: change from 1.KBH to 2.JV7,NaN
69,8-May-26,A4,DEM2-SR-0014,"delete section KLM submitted on Wed, 22-Apr-20...",NaN
70,NaN,A1,DEM1-SR-0355,wrong selection in C3. Change Male to Female.,NaN

:

:

In [ ]:
df.isna().sum()

Date report issue    36
Form                  0
Participant ID        0
Correction            0
Status               71
dtype: int64

:

:

In [ ]:
df.shape

(71, 5)

:

:

In [ ]:
df['Form'].value_counts()

Form
A1            36
A4            18
D1             6
A1, B1, D1     3
D5             2
B1             2
C4             1
D4             1
B2             1
C8             1
Name: count, dtype: int64

:

:

In [ ]:
df['Participant ID'].value_counts()

Participant ID
DEM1-PP-0034    2
DEM2-PP-0029    2
DEM1-PP-0003    2
DEM2-PP-0007    2
DEM1-PP-0020    2
               ..
DEM2-PP-0060    1
DEM2-PP-0011    1
DEM1-PP-0009    1
DEM1-SR-0134    1
DEM1-SR-0355    1
Name: count, Length: 63, dtype: int64

:

:

In [ ]:
df = df[df['Form'] == 'A1']
df

,Date report issue,Form,Participant ID,Correction,status
0,24-Nov-25,A1,DEM1-PP-0034,"Delete this data submitted on 20 Nov 2025, it'...",NaN
1,25-Nov-25,A1,DEM1-PP-0009,C8. change 5 to 1 cuz the guardian change job ...,NaN
5,NaN,A1,DEM1-PP-0040,A7. change Dx from Goiter to Congenital Hypoth...,NaN
6,4-Dec-25,A1,DEM1-PP-0011,"Delete data submitted on Thu, 04 Dec at 8:32 b...",NaN
9,NaN,A1,DEM1-PP-0020,A3: change date from 12 Dec 2025 to 28 Nov 2025,NaN
10,NaN,A1,DEM1-PP-0075,A3: change date from 12 Dec 2025 to 11 Dec 2025,NaN
11,22-Dec-25,A1,DEM1-PP-0003,A6: change 22.PICU to 2.C2,NaN
12,NaN,A1,DEM1-PP-0019,"A7: change diagnostic ""infrastructure"" to ""arm...",NaN
13,NaN,A1,DEM1-PP-0025,"A7: change diagnostic ""infrastructure"" to ""arm...",NaN
14,NaN,A1,DEM1-PP-0026,"A7: change diagnostic ""infrastructure"" to ""arm...",NaN
15,NaN,A1,DEM1-PP-0032,"A7: change diagnostic ""infrastructure"" to ""arm...",NaN
17,NaN,A1,DEM1-PP-0149,submitted 2 records: 1st without section H.chi...,NaN
18,2-Jan-26,A1,DEM1-PP-0158,"A7: change diagnostic ""leg"" to ""led pain""",NaN
22,30-Jan-26,A1,DEM2-PP-0047,Delete this submission because MI submitted in...,NaN
23,11-Feb-26,A1,DEM1-PP-0305,"A7: change diagnostic ""acute tonsillitis"" to ""...",NaN
38,NaN,A1,DEM2-PP-0078,"Delete the one submitted on 25/03/2026, submit...",NaN
46,31-Mar-26,A1,DEM1-PP-0003,"Delete the one submitted on 2025-11-26 , submi...",NaN
47,NaN,A1,DEM1-PP-0004,"Delete the one submitted on 2025-11-26 , submi...",NaN
48,NaN,A1,DEM1-PP-0020,"Delete the one submitted on 2026-02-02 , submi...",NaN
49,NaN,A1,DEM1-PP-0034,"Delete the one submitted on 2025-11-20 , submi...",NaN
50,NaN,A1,DEM1-PP-0041,Delete the one submitted on 2026-01-12T08:01:2...,NaN
52,NaN,A1,DEM1-PP-0219,Delete the one submitted on 2026-01-16T02:13:1...,NaN
53,NaN,A1,DEM1-PP-0220,Delete the one submitted on 2026-01-16T02:14:2...,NaN
54,NaN,A1,DEM1-PP-0352,Delete the one submitted on 2026-03-09T07:37:4...,NaN
55,NaN,A1,DEM1-PP-0049,Delete the one submitted on 2025-12-08T07:23:0...,NaN
56,2-Apr-26,A1,DEM1-PP-0412,Delete submission on 01.04.2026,NaN
57,NaN,A1,DEM1-PP-0206,Delete the one submitted on 2026-01-15T02:33:1...,NaN
58,NaN,A1,DEM1-PP-0042,Delete the one submitted on 2025-12-04T03:44:5...,NaN
59,NaN,A1,DEM1-PP-0119,Delete the one submitted on 2025-12-26T03:44:4...,NaN
60,NaN,A1,DEM1-PP-0090,Delete the one submitted on 2025-12-30T09:34:5...,NaN
61,NaN,A1,DEM1-PP-0182,Delete the one submitted on 2026-01-09T04:00:0...,NaN
62,6-Apr-26,A1,DEM1-SR-0214,delete submission on 06 April 2026 at 11:25 fr...,NaN
65,NaN,A1,DEM1-SR-0242,delete Submit on 09 April 2026 at 11:24 Tablet...,NaN
66,23-Apr-26,A1,DEM1-SR-0281,C3: changed Male to Female. ( Submit on 23-04-...,NaN
67,24-Apr-26,A1,DEM1-SR-0269,delete submission from T11 at 10:17 22.04.2026...,NaN
70,NaN,A1,DEM1-SR-0355,wrong selection in C3. Change Male to Female.,NaN

:

:

In [ ]:
url_a1 = utils.url_a1

:

:

In [ ]:
def get_data_url(form_id):

    url = "https://demele-jev.uhs.edu.kh/api/download-submissions-v3"

    params = {
        "formId": form_id,
        "secret_key": "13ac3c2f-b7df-4ce9-8010-247da09a91d9",
        "splitSelectMultiples": "true",
        # "groupPaths": "false",
        "deletedFields": "true"
    }

    response = requests.get(
        url,
        params=params,
        timeout=10
    )

    response.raise_for_status()

    df = pd.read_csv(StringIO(response.text))

    return df

:

: